FROM node:16-alpine
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /opt/
COPY ./package.json ./
ENV PATH /opt/node_modules/ .bin:$PATH
RUN npm install --omit=dev
WORKDIR /opt/app
COPY ./ .
COPY ./public/uploads/ /public/uploads/
COPY ./src/api/ /src/api/
RUN npm run build

ENV NODE_ENV=production
ENV STRAPI_LOG_LEVEL=debug

EXPOSE 1337

CMD ["npm","run", "start"]
